on: [push, delete, pull_request, workflow_dispatch, create]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github) }}
      - run: echo ${{ toJson(job) }}
      - run: echo ${{ toJson(steps) }}
      - run: echo ${{ toJson(runner) }}
