on: [push, delete, pull_request, workflow_dispatch, create]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github:${{ toJson(github) }}"
      - run: echo "event:${{ toJson(github.event) }}"
      - run: echo "job:${{ toJson(job) }}"
      - run: echo "steps:${{ toJson(steps) }}"
      - run: echo "runner:${{ toJson(runner) }}"
